// flow-typed signature: b142b989c0bae154d81d84f6153c521d
// flow-typed version: <<STUB>>/hex-to-binary_v^1.0.1/flow_v0.128.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hex-to-binary'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hex-to-binary' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'hex-to-binary/index' {
  declare module.exports: $Exports<'hex-to-binary'>;
}
declare module 'hex-to-binary/index.js' {
  declare module.exports: $Exports<'hex-to-binary'>;
}
